"""init

Revision ID: 27226862299a
Revises: 
Create Date: 2025-08-13 06:54:32.347184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27226862299a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HOTEL', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('beds24_prop_key', sa.String(length=128), nullable=False),
    sa.Column('beds24_api_key', sa.String(length=256), nullable=False),
    sa.Column('ttlock_client_id', sa.String(length=128), nullable=True),
    sa.Column('ttlock_client_secret', sa.String(length=256), nullable=True),
    sa.Column('ttlock_access_token', sa.String(length=512), nullable=True),
    sa.Column('default_checkin_time', sa.String(length=5), nullable=True),
    sa.Column('default_checkout_time', sa.String(length=5), nullable=True),
    sa.Column('pin_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('booking_number_internal', sa.String(length=64), nullable=True),
    sa.Column('booking_number_portal', sa.String(length=64), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('room_number', sa.String(length=64), nullable=True),
    sa.Column('access_start', sa.DateTime(), nullable=True),
    sa.Column('access_end', sa.DateTime(), nullable=True),
    sa.Column('pin_code', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ttlock_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FRONT', 'HALLWAY', 'ROOM', name='doortype'), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('range_start', sa.Integer(), nullable=True),
    sa.Column('range_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doors')
    op.drop_table('booking_sync_logs')
    op.drop_table('hotels')
    op.drop_table('users')
    # ### end Alembic commands ###
